In [12]:
import numpy as np
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [13]:
arr[5]

5

In [18]:
teil_arr = arr[0:6]
print(teil_arr)

[0 1 2 3 4 5]


In [19]:
teil_arr[:] = 99

In [20]:
print(arr)


[99 99 99 99 99 99  6  7  8  9 10]


In [21]:
arr_kopie = arr.copy()
print(arr_kopie)


[99 99 99 99 99 99  6  7  8  9 10]


In [22]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [26]:
arr = np.arange(1,11)

In [29]:
bool_array = arr > 5
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [30]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [31]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [35]:
arr_2d[1:3, 3:]

array([[13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29]])